# Generated by Django 6.0.2 on 2026-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='espn_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='espn_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='espn_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
