# Generated by Django 6.0.2 on 2026-03-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_sport_espn_id_alter_game_espn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='espn_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='espn_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('sport', 'espn_id')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('sport', 'espn_id')},
        ),
    ]
