# Generated by Django 5.2.12 on 2026-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_game_espn_id_alter_team_espn_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='alternate_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
