# Generated by Django 6.0.3 on 2026-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_sport_color_team_alternate_color_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='leg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='round_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='total_legs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
