# Generated by Django 6.0.3 on 2026-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_game_leg_game_round_name_game_total_legs'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
