# Generated by Django 6.0.3 on 2026-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_game_away_rank_game_home_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='record',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
