# Generated by Django 6.0.3 on 2026-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_team_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='leaderboard',
            field=models.TextField(blank=True, default=''),
        ),
    ]
