# Generated by Django 6.0.3 on 2026-03-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_game_broadcast_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='broadcast_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='leaderboard',
        ),
    ]
