# Generated by Django 6.0.3 on 2026-03-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_remove_game_broadcast_time_remove_game_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='headshot_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='reach',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='stance',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
