# Generated by Django 6.0.3 on 2026-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_team_age_team_headshot_url_team_height_team_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
