# Generated by Django 5.2.12 on 2026-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_game_card_type'),
        ('services', '0002_usersportpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='streaming_services',
            field=models.ManyToManyField(blank=True, related_name='games_all', to='services.streamingservice'),
        ),
    ]
