# Generated by Django 5.2.12 on 2026-03-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_game_streaming_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='streaming_service',
        ),
    ]
