# Generated by Django 5.2.12 on 2026-03-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_remove_game_streaming_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
