# Generated by Django 5.2.12 on 2026-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_game_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tbd_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
