name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /opt/gamestream

            # 1. Update the code on the server
            sudo git fetch origin main
            sudo git reset --hard origin/main

            # 2. Use Compose to handle the build and restart
            sudo docker-compose down
            sudo docker-compose up -d --build

            # 3. Clean up old, unused images to save disk space on AWS
            sudo docker image prune -f

            #3.1 Ensure staticfiles directory is owned by www-data for collectstatic to work
            sudo chown -R ubuntu:www-data /opt/gamestream/staticfiles
            sudo chmod -R 755 /opt/gamestream/staticfiles

            # 4. Run migrations inside the new container & collect static files 
            sudo docker-compose exec -T web python3 manage.py migrate --noinput
            sudo docker-compose exec -T web python3 manage.py collectstatic --noinput

            # 5. Refresh Apache
            sudo systemctl restart apache2


            # 6. Set up daily cron job to fetch schedule (runs every 3 hours to ensure schedule is up to date, especially for timezones)
            (crontab -l 2>/dev/null | grep -v "fetch_schedule"; echo "0 */3 * * * cd /opt/gamestream && /usr/local/bin/docker-compose exec -T web python manage.py fetch_schedule >> /var/log/fetch_schedule.log 2>&1") | crontab -

            # 7. Clean up games without streaming services
            sudo docker-compose exec -T web python manage.py shell -c "from schedules.models import Game; Game.objects.filter(streaming_service__isnull=True).delete()"
          EOF

      - name: Cleanup SSH key
        if: always()
        run: rm -f ec2_key.pem
